platform: linux

inputs:
  - name: pypi.git

outputs:
  - name: wheel

run:
  path: sh
  args:
  - -exc
  - |
    apt-get -q update
    apt-get -yq install virtualenv
    pip install --upgrade pip && \
    pip --no-input install pipenv
    cd pypi.git && pipenv run make wheel
    cp -r Dockerfile dist ../wheel/
