platform: linux

inputs:
  - name: pypi.git
  - name: version

outputs:
  - name: dist

run:
  path: sh
  args:
  - -exc
  - |
    export VERSION=`cat version/version`
    cd pypi.git/test/test_package1_3
    python setup.py bdist_wheel
    mv dist/*.whl ../../../dist/  
