platform: linux

inputs:
  - name: pypi.git

outputs:
  - name: dist

run:
  path: sh
  args:
  - -exc
  - |
    cd pypi.git/test/test_package1_3
    python setup.py bdist_wheel
    mv dist/*.whl ../../../dist/  
