---
resource_types:

- name: pypi
  type: docker-image
  source:
    repository: cfplatformeng/concourse-pypi-resource
    tag: {{pypi-resource-tag}}

resources:

- name: code
  type: git
  source:
    uri: http://github.com/cf-platform-eng/concourse-pypi-resource

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:cf-platform-eng/test-python-package
    branch: master
    file: version
    private_key: {{github-private-key}}

- name: package-repo
  type: git
  source:
    uri: http://github.com/cf-platform-eng/test-python-package

- name: pypi-package
  type: pypi
  source:
    name: cf-platform-eng
    test: true
    username: {{pypi-username}}
    password: {{pypi-password}}

jobs:

- name: unit-test
  plan:
  - get: code
    trigger: true
  - task: run-unit-tests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: python
          tag: '2'
      inputs:
      - name: code
      run:
        path: sh
        args:
        - -exc
        - |
          apt -q update
          apt -yq install pipenv
          cd code && pipenv run make test

- name: check-and-get
  plan:
  - get: pypi-package

- name: out
  plan:
  - put: version
    params:
      bump: patch
  - get: package-repo
  - task: build-package
    config:
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: latest
      platform: linux
      inputs:
      - name: package-repo
      outputs:
      - name: package-out
      run:
        path: sh
        args:
        - -exc
        - |
          cd package-repo
          python setup.py sdist
          cp dist/*.tar.gz ../package-out/
  - put: pypi-package
    params:
      glob: package-out/*.tar.gz
