project: concourse-pypi-resource-pipeline
docker_tag_add_file:
semver_initial_version: 0.0.0
semver_key: artifacts/concourse-example-pypi-dev/version
pci-gchat_hook: ((gchat_hook_sandobox_integration_team))
trigger: false
team: developers
